# -*- coding: utf-8 -*-
"""spam_email

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_RLMrm1EpNg1GBfRRzgB5ZBS2ZE9zYz

# **Spam Email Detector**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,classification_report
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers,models
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping
from nltk.corpus import stopwords
import re
import nltk

data = pd.read_csv("emails.csv")
print(data.head())

print(data.shape)

x = data["text"]
y = data["spam"]

nltk.download("stopwords")
stop_words = set(stopwords.words("english"))
print(stop_words)

def clean_text(text):
  text = text.lower()
  text = re.sub(r"[^\w\s]","",text)
  text = " ".join([words for words in text.split() if words not in stop_words])
  return text

data["Cleaned_data"] = data["text"].apply(clean_text)
print(data.head())

def token(text):
  tokenizer = Tokenizer()
  tokenizer.fit_on_texts(text)
  sequence = tokenizer.texts_to_sequences(text)
  max_len_seq = max(len(x) for x in sequence)
  padded_sequence = pad_sequences(sequence,maxlen = max_len_seq)
  return tokenizer,sequence,padded_sequence,max_len_seq
tokenizer,sequence,padded_sequence,max_sequence_len = token(data["text"])
print(sequence[:1])

x_train,x_test,y_train,y_test = train_test_split(padded_sequence,y,test_size=0.1,random_state = 42)
print(x_train.shape)
print(x_test.shape)

model = models.Sequential([
    layers.Embedding(input_dim=len(tokenizer.word_index)+1,output_dim = 100,input_length = max_sequence_len),
    layers.LSTM(128),
    layers.Dropout(0.2),
    layers.Dense(256,activation = "relu"),
    layers.Dense(1,activation = "sigmoid")
])

model.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"])
model.summary()

model.fit(x_train,y_train,batch_size = 32,epochs = 2,validation_split = 0.1)

test_loss,test_accuracy = model.evaluate(x_test,y_test)
print(test_accuracy)
print(test_loss)

model.save("spam_detector.h5")

model.save("spam_detector_.keras")

#from tensorflow.keras.models import load_model

#model = load_model("spam_model.keras")

import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

#import pickle

#with open("tokenizer.pkl", "rb") as f:
    #tokenizer = pickle.load(f)

print("Spam Email Detector")
email = input("Enter your Email: ")
clean_text(email)
temail,semail,pemail,memail = token(email)
spam_pred = model.predict(pemail)
prediction = spam_pred[0][0]
if prediction > 0.5:
  print("Spam Email")
else:
  print("Not a Spam Email")